### ISSUE TITLE
Fog/Map reveal

### ISSUE THREAD

**Issue by cpytel** [tableparty/table#3]
This seems like a feature we need to be viable. Please correct me if you feel differently.

The approach I’m thinking of for this is to build a grid a opaque elements over the map image that are the same size as the individual map squares. These elements could be individually toggled on and off.

I was thinking that the map would persist which parts were visible to the db, and they’d be synced to all the clients.

As a second pass, I’m thinking the campaign could know who the dm is, so that the dm would have 50% translucent instead of opaque elements, and be the only one who can toggle them.

thoughts?

**Comment by jdbann** [comment]
A very interesting question. I could go either way on this feature.

First a quick note on the 'grid'. In my experiments with Roll20, I found it to be one of the more frustrating parts. It was very difficult to reliably get their grid to match the grid included on the map image. As a result, I had not been intending to implement any specific grid mechanic (snapping/measuring etc). That doesn't prevent us from being able to crop or mark particular areas though.

D&D has three core pillars to the game: [exploration, social interaction, and combat](https://dnd.wizards.com/articles/unearthed-arcana/3pillarxp). The map can be useful for all three, but will mostly be used in exploration and combat. However, I would say that they don't have the same mapping requirements.

Let's use Dwarven Excavation as an example:

![Original Dwarven Excavation map](https://user-images.githubusercontent.com/1191840/77230895-812e1e00-6b8f-11ea-8ef9-d8903efd015c.jpg)

_Quick caveat that this is a specific situation where I am working with a digital copy of an existing map rather than creating my own. When we play in person, I copy up the maps to 1" scale and can easily omit things._

For exploration, the whole map contains plenty of spoilers. The secret doors are marked out, the entire geography of the temple is revealed, and to some extend the amount of area mapped indicates where events might happen.

If I try to cover up some of the secret rooms, I can mostly deal with the secret doors and the hidden rooms:

![Dwarven Excavation map edited to disguise hidden areas](https://user-images.githubusercontent.com/1191840/77231071-7922ae00-6b90-11ea-84f0-ba0cca4e448a.jpg)

The position of the structure in the map gives away a lot though and the rooms wont go beyond the boundaries of the image.

In our first session, when we explored Gnomengarde, we had a far more complicated dungeon which offered a lot more in the way of exploration:

![Original Gnomengarde map](https://user-images.githubusercontent.com/1191840/77231315-fb5fa200-6b91-11ea-9386-beed583e77e7.jpg)

I chose not to create a tabletop map and instead narrated the whole excursion. When geography was particularly important, I sketched some things on paper.

When it comes to combat, the geography is quite critical for making decisions as a player. I quite like providing maps for combat because I want players to have the opportunity to do cool stuff with their environment. Also, range and positioning are far more critical to how events unfold.

For combat then, I would be hoping to focus the attention more to these areas:

![Dwarven Excavation ooze encounter area](https://user-images.githubusercontent.com/1191840/77231509-52b24200-6b93-11ea-82ce-0b7595dc61b1.jpg)

![Dwarven Excavation orc encounter area](https://user-images.githubusercontent.com/1191840/77231515-5e056d80-6b93-11ea-93da-2e03a6e01c76.jpg)

I'd be keen to understand how the map affects the experience of a player. I'm aware I did an equivalent of revealing areas of the map whilst you explored Dwarven Excavation...

**Comment by jdbann** [comment]
Sly Flourish (very good for DM advice) does talk about sharing tightly cropped screenshots of maps for exploration when using Discord: https://slyflourish.com/playing_dnd_over_discord.html

Perhaps rather than fog/map reveal it's more about cropping from a larger map?

But then that's just a half-full/empty thing at that point 😂

**Comment by cpytel** [comment]
I think it makes sense to try playing without this for a while.

**Comment by jdbann** [comment]
I've been thinking about using an SVG mask for this purpose. The DM could effectively paint out areas they'd like to reveal to the users and it would be pretty easy to replicate across sessions.

**Comment by jdbann** [comment]
Had a play with SVG masks this morning...

![Kapture 2020-05-09 at 12 20 45](https://user-images.githubusercontent.com/1191840/81472368-9585b300-91ef-11ea-8a97-2c09ded01059.gif)

It's created by appending circle elements to an SVG mask, so to store this we just need an array of coordinates.

I'd need to spend a bit of time getting it to work with zooming and ensuring that the tokens can still be interacted with etc but what do you think of the approach and result?

**Comment by cpytel** [comment]
Looks cool. The only reason why I was thinking of building a grid of elements that sit over the map that could be individually toggled on and off was so that it’s be easier to interact with the elements underneath once the fog in that area was removed because they would literally not be there.

If you think we can work around the token and map interaction, that’s ok with me.

As a DM has your thinking on the need for map visibility changed?

**Comment by jdbann** [comment]
I've just tested my theory about the token and map interaction and it is doable. The fog layer can be given `pointer-events: none;` and then we're all set.

However, dragging performs poorly in Safari and Chrome has some weird visual artefacts when you move tokens.

My thinking on map visibility hasn't really changed so much. But it was specifically requested by a couple of players so now I'm outnumbered 😝 The main thing I want to avoid is having all the activity of the game centre around maps. I like that this tool was something we switched to when it was helpful rather than lived inside for the whole session.
